spring:
  server:
    port: 8080
  datasource:
    url: jdbc:h2:tcp://localhost/~/api
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: create
  messages:
    basename: i18n/exception/exception
    encoding: UTF-8